<div class="block block-blog">
    <!--<div class="block-title">
        <strong><span><?php // echo Mage::getStoreConfig('blog/blog/title'); ?></span></strong>
    </div>-->
    <div class="block-content">
        <?php if ($posts = $this->getRecent()): ?>
            <div class="menu-recent view">
                <dt class="block-title"><strong><span><?php echo Mage::helper('blog')->__('Recent Posts'); ?></span></strong></dt>
                <dd>
                <ol>
                    <?php foreach ($posts as $post): ?>
                        <li><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ol>
                </dd>
            </div>
        <?php endif; ?>

        <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
            <div class="menu-categories view">
                <dt class="block-title"><strong><span><?php echo Mage::helper('blog')->__('Categories'); ?></span></strong></dt>
                <dd>
                <ol>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ol>
                </dd>
            </div>
        <?php endif; ?>

        <?php echo $this->getChildHtml('blog_tags'); ?>
    </div>
</div>