/*
Do not change this file it lost your changes.
*/

<?php
$instance = Mage::helper("ExtraConfig");
$store = Mage::app()->getRequest()->getParam('store');
$responsive = Mage::getStoreConfig('themelayout/layout/responsiveness',$store);
$width = Mage::getStoreConfig('themelayout/layout/layout_width',$store);
$customwidth = Mage::getStoreConfig('themelayout/layout/custom_width',$store);
$fluidwidth = Mage::getStoreConfig('themelayout/layout/fluid_width',$store);
$responsivewidth = $instance->responsivewidth();
$maxwidth = $instance->maxwidth($store);
$maxbreak = $instance->breakpoint($maxwidth, $store);
?>


/* ********************************************************************************************
	Grid container
*********************************************************************************************** */

    <?php if($responsive){ ?>
	.container_12 {
	    width:96%;
	    <?php if ($maxbreak == 960){ ?>
		    <?php if ($width == 'custom'){ ?>
			    max-width: <?php echo $customwidth; ?>px;
		    <?php } else { ?>
			    max-width: <?php echo $responsivewidth['960']; ?>px;
		    <?php } ?>    
	    <?php } else { ?>
		    <?php if (!$fluidwidth){ ?>
		    max-width: <?php echo $responsivewidth['960']; ?>px;
		    <?php } ?>
	    <?php } ?>	
	}
	
	/*
	Forces backgrounds to span full width,
	even if there is horizontal scrolling.
	Increase this if your layout is wider.
      
	Note: IE works fine without this fix.
	*/
	
        <?php if ($width == 'custom'){ ?>
		.ie8 .container_12 { max-width:<?php echo $customwidth; ?>px; }
	<?php } else { ?>
		.ie8 .container_12 { max-width:<?php echo $responsivewidth[$width]; ?>px; }
	<?php } ?>
        
	<?php } else { ?>
	
	    <?php 
		    $nonresponsivewidth = 0;
		    if ($width == 'custom') {
			$nonresponsivewidth = $customwidth;
		    } else {
			$nonresponsivewidth = $responsivewidth[$width];
		    }
	    ?>
	    .container_12 {
		    width: <?php echo $nonresponsivewidth; ?>px !important;
	    }
	    
	<?php } ?>
    
    <?php if($responsive){ ?>
    
    
<?php if($maxbreak >= 1920) { ?>

/* ********************************************************************************************
    Desktop - design for a width of 1920px
*********************************************************************************************** */

/* 1680px <= width */

@media only screen and (min-width: 1920px) {

        <?php if($maxbreak == 1920){ ?>
            <?php if($width == 'custom') { ?>
                .container_12 { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container_12 { max-width:<?php echo $responsivewidth['1920']; ?>px; }
            <?php } ?>
	<?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container_12 { max-width:<?php echo $responsivewidth['1920']; ?>px; }
            <?php } ?>
        <?php } ?>
	
	/* Hide */
	.hide-below-1680 { display:inherit !important; }
	.hide-below-1440 { display:inherit !important; }
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
	
}
<?php } ?>


<?php if($maxbreak >= 1680) { ?>

/* ********************************************************************************************
    Desktop - design for a width of 1680px
*********************************************************************************************** */

/* 1680px <= width */

@media only screen and (min-width: 1680px) <?php if($maxbreak > 1680){ ?>and (max-width: 1919px)<?php } ?> {

        <?php if($maxbreak == 1680){ ?>
            <?php if($width == 'custom') { ?>
                .container_12 { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container_12 { max-width:<?php echo $responsivewidth['1680']; ?>px; }
            <?php } ?>
	<?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container_12 { max-width:<?php echo $responsivewidth['1680']; ?>px; }
            <?php } ?>
        <?php } ?>
	
	/* Hide */
	.hide-below-1680 { display:inherit !important; }
	.hide-below-1440 { display:inherit !important; }
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
	
}
<?php } ?>


<?php if($maxbreak >= 1440) { ?>


/* ********************************************************************************************
    Desktop - design for a width of 1440px
*********************************************************************************************** */

/* 1440px <= width */

@media only screen and (min-width: 1440px) <?php if($maxbreak > 1440){ ?>and (max-width: 1679px)<?php } ?> {

	<?php if($maxbreak == 1440){ ?>
            <?php if($width == 'custom') { ?>
                .container_12 { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container_12 { max-width:<?php echo $responsivewidth['1440']; ?>px; }
            <?php } ?>
        <?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container_12 { max-width:<?php echo $responsivewidth['1440']; ?>px; }
            <?php } ?>
        <?php } ?>
	
	/* Hide */
	.hide-below-1440 { display:inherit !important; }
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
	
}
<?php } ?>


<?php if($maxbreak >= 1360 ) { ?>

/* ********************************************************************************************
    Desktop - design for a width of 1366px and 1360px
*********************************************************************************************** */

/* 1360px <= width */

@media only screen and (min-width: 1360px) <?php if($maxbreak > 1360){ ?>and (max-width: 1439px)<?php } ?> {

	<?php if($maxbreak == 1360){ ?>
            <?php if($width == 'custom') { ?>
                .container_12 { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container_12 { max-width:<?php echo $responsivewidth['1360']; ?>px; }
            <?php } ?>
        <?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container_12 { max-width:<?php echo $responsivewidth['1360']; ?>px; }
            <?php } ?>
        <?php } ?>
	
	/* Hide */
	.hide-below-1360 { display:inherit !important; }
	.hide-below-1280 { display:inherit !important; }
	
}
<?php } ?>


<?php if($maxbreak >= 1280) { ?>

/* ********************************************************************************************
    Desktop - design for a width of 1280px
*********************************************************************************************** */

/* 1280px <= width */

@media only screen and (min-width: 1280px) <?php if($maxbreak > 1280){ ?>and (max-width: 1359px)<?php } ?> {

	<?php if($maxbreak == 1280){ ?>
            <?php if($width == 'custom') { ?>
                .container_12 { max-width:<?php echo $customwidth; ?>px; }
            <?php } else { ?>
                .container_12 { max-width:<?php echo $responsivewidth['1280']; ?>px; }
            <?php } ?>
	<?php } else { ?>
            <?php if (!$fluidwidth){ ?>
                .container_12 { max-width:<?php echo $responsivewidth['1280']; ?>px; }
            <?php } ?>
        <?php } ?>
	
	/* Hide */
	.hide-below-1280 { display:inherit !important; }
	
}
<?php } ?>


/* ********************************************************************************************
    Design for a width of less than 1024 px
*********************************************************************************************** */

/* width < 1024px */

@media only screen and (max-width: 1023px) {

	/* Hide */
	.hide-below-1024 { display:none !important; }
	
}


/* ********************************************************************************************
    Tablet (Portrait) - design for a width of 768px
*********************************************************************************************** */

/* 768px <= width < 960px */

@media only screen and (min-width: 768px) and (max-width: 959px) {

        <?php if (!$fluidwidth){ ?>
            .container_12 { max-width:737px; }
        <?php } ?>
		
	/* Hide */
	.hide-below-960 { display:none !important; }
	
}

/* ********************************************************************************************
    All mobile - design for a width of less than 768px
*********************************************************************************************** */

/* width < 768px */

@media only screen and (max-width: 767px) {
	
	/* Containers (Display full width and add side padding) */
	.container_12 { width:92%; padding-left:2%; padding-right:2%; }
	.pull-container { width:100%; margin-left:auto; }
	
	/* Grid >> Global (Remove both margin and display full width ) */
	.grid_1,
	.grid_2,
	.grid_3,
	.grid_4,
	.grid_5,
	.grid_6,
	.grid_7,
	.grid_8,
	.grid_9,
	.grid_10,
	.grid_11,
	.grid_12,
	.grid_full {
		width:100% !important;
		margin-left:0;
		margin-right:0;
	}
	
	.no-both-margin.mobile-grid-half img{margin: 0 auto; display:table;}

	/* Vertically aligned grid
	======================================================================================= */
	.v-grid-container { display:block; }
	.v-grid { float:left; display:block; width:100%; }
	
}


/* ********************************************************************************************
    Mobile (Landscape) - design for a width of 480px
*********************************************************************************************** */

/* 480px <= width < 768px */

@media only screen and (min-width: 480px) and (max-width: 767px) {

        <?php if (!$fluidwidth){ ?>
            .container_12 { max-width:440px; }
        <?php } ?>
		
	/* Hide */
	.hide-below-960 { display:none !important; }
	.hide-below-768 { display:none !important; }
	
	/* Mobile Grid Half Units Avalaible */
	.mobile-grid-half { width:48% !important; margin-left:1%; margin-right:1%; float:left;}
	
	/* Remove Left Margin */
	.no-left-margin.mobile-grid-half { width:49% !important; margin-left:0%;}
	
	/* Remove Right Margin */
	.no-right-margin.mobile-grid-half { width:49% !important;margin-right:0%; }
	
	/* Remove Both Margin */
	.no-both-margin.mobile-grid-half { width:50% !important; margin-left:0%; margin-right:0%; }
	
}


/* ********************************************************************************************
    Mobile (Landscape, iPhone 4 Portrait) - design for a width of 640px
*********************************************************************************************** */

/* 640px <= width < 768px */

@media only screen and (min-width: 640px) and (max-width: 767px) {

	<?php if (!$fluidwidth){ ?>
	    .container_12 { max-width:590px; }
	<?php } ?>
	
}


/* ********************************************************************************************
    Design for a width of less than 480px (small mobile)
*********************************************************************************************** */

/* width < 480px */

@media only screen and (max-width: 479px) {

	/* Containers (Display full width and add side padding) */
	.container_12 { max-width:none !important; width:94%; padding-left:3%; padding-right:3%; }
	
	/* Mobile Grid Half Units Avalaible (Use Onlye Header Nav) */
	.nav .mobile-grid-half { width:48% !important; margin-left:1%; margin-right:1%; float:left;}
	
	/* Remove Left Margin */
	.nav .no-left-margin.mobile-grid-half { width:49% !important; margin-left:0%;}
	
	/* Remove Right Margin */
	.nav .no-right-margin.mobile-grid-half { width:49% !important;margin-right:0%; }
	
	/* Remove Both Margin */
	.nav .no-both-margin.mobile-grid-half { width:50% !important; margin-left:0%; margin-right:0%; } 		

}


/* ********************************************************************************************
    Mobile (Portrait) - design for a width of 320px
*********************************************************************************************** */

/* 320px <= width < 480px */

@media only screen and (min-width: 320px) and (max-width: 479px) {

	<?php if (!$fluidwidth){ ?>
	    /* .container_12 { max-width:301px; } */
	<?php } ?>
	
	/* Hide */
	.hide-below-960 { display:none !important; }
	.hide-below-768 { display:none !important; }
	.hide-below-480 { display:none !important; }
	
}


/* ********************************************************************************************
    Mobile (Portrait) - design for a width of less than 320px
*********************************************************************************************** */

/* width < 320px */

@media only screen and (max-width: 319px) {

	<?php if (!$fluidwidth){ ?>
	    /* .container_12 { max-width:226px; } */
	<?php } ?>
	.container_12 { max-width:none !important; width:92%; padding-left:4%; padding-right:4%; }

	/* Hide */
	.hide-below-960 { display:none !important; }
	.hide-below-768 { display:none !important; }
	.hide-below-480 { display:none !important; }
	.hide-below-320 { display:none !important; }
	
}


<?php } ?>