<?php if(Mage::getStoreConfig('multiproduct/block6/enable')) : ?>
<?php 
$_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    
?>
<?php if($_productCollection->count()): ?>
<?php $_collectionSize = $_productCollection->count() ?>
<div class="block-reviews">
	<div class="section-line">
	    <h2><?php echo $this->__('Top Rated') ?></h2>
	</div>
	<ul class="mini-products-list">
		<?php $i=0;$j=0; foreach ($_productCollection as $_product): ?>
			<li class="item">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image">	
					<img width="72" height="80" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(72, 0) ?>"  alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
				</a>
				<div class="product-details">
					<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()); ?></a></h3>
					<?php echo $this->getPriceHtml($_product, true) ?>
					<?php echo $this->getReviewsSummaryHtml($_product, false, true); ?>
				</div>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
<?php endif; ?>