<?php
/**
 * Moo Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Moo
 * @package    Moo_Catalog
 * @author     Mohamed Alsharaf <mohamed.alsharaf@gmail.com>
 * @copyright  Copyright (c) 2010 Mohamed Alsharaf. (http://jamandcheese-on-phptoast.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$newsaleicon = Mage::getStoreConfig('mygeneral/product_list/newsaleicon');
?>
<?php
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
	
	
	$gallery .= '<div id="more-images-slider" class="itemslider-thumbnails">';
	
	foreach ($galleryImages as $_image) {	
		$gallery .= '<div class="item">'
			. '<a id="cloud-zoom-gallery' . $i . '" href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
			. 'rel="useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) . '\'" class="cloud-zoom-gallery product-image" title="' . $this->htmlEscape($_image->getLabel()) . '">'
			. '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(120, 0) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
			. '</a></div>';		
	}
	$gallery .= '</div>';
}
?>

<?php $label = "";?>
<?php if($newsaleicon == '1') { ?> 
	<?php $gdate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
	$g= 0;
	if($_product->special_from_date != null && $_product->special_to_date == "")
	{
	    if( $gdate >= $_product->special_from_date)
	    {
		    $g = 1; 
	    }
	}
	if($_product->special_from_date != "" && $_product->special_to_date != "")
	{
	    if($gdate >= $_product->special_from_date && $gdate <= $_product->special_to_date)
	    {
	    $g = 1; 
	    }
	}
	    
	if($g == 1){
	    $label ='<div class="sale"><label>'.$this->__('SALE').'</label></div>';
	} ?>
	
	
      <?php $hdate = date('Y-m-d');
	$h= 0;
	if($_product->news_from_date != null && $_product->news_to_date == "")
	{
	    if( $hdate >= $_product->news_from_date)
	    {
		    $h = 1; 
	    }
	}
	if($_product->news_from_date != "" && $_product->news_to_date != "")
	{
	    if($hdate >= $_product->news_from_date && $hdate <= $_product->news_to_date)
	    {
	    $h = 1; 
	    }
	}
	if($h == 1){ 
	    $label .= '<div class="new"><label>'.$this->__('NEW').'</label></div>';
	}?>  
<?php } ?>              





    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
	<div class="img-box">
	    <div class="product-image product-image-zoom">
		
		<a rel="<?php echo $this->renderCloudOptions(); ?>" <?php echo $this->renderLightboxOptions(); ?> gallery="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
		    <?php echo $label; ?>
		    <?php
		    $_img = '<img id="image" src="' . $this->getCloudImage($_product) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
		    echo $_helper->productAttribute($_product, $_img, 'image');
		    ?>
		</a>
	    </div>
	    <?php if (isset($gallery)): ?>
		<?php echo $gallery; ?>
	    <?php endif; ?>    
	</div>

    <?php else: ?>
	<div class="product-image">
	    <?php
	    $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(588) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
	    echo $_helper->productAttribute($_product, $_img, 'image');
	    ?>
	</div>

   <?php endif; ?>

<script>
//<![CDATA[
jQuery(function(j$) {
	j$("#more-images-slider").owlCarousel({
	    itemsCustom : [
		[0, 3],
		[341, 4],
		[430, 5],
		[623, 6],
		[751, 4],
		[943, 5],
		[1263, 6]
	    ]<?php echo Mage::helper("ExtraConfig")->sliderSetting(); ?>
	});	
});
//]]>
</script>